const Sequelize = require('sequelize');
const db = require('../db/connection');

const Revenue_upload = db.define('revenue_upload',{
    id:{
        type: Sequelize.BIGINT(20),
        autoIncrement: true,
        primaryKey: true,
        allowNull : true
    },
    revenue_type: Sequelize.STRING(50),
    biller_accountid: Sequelize.STRING(250),
    assessment_no: Sequelize.STRING(250),
    revenue_code: Sequelize.STRING(250),
    bill_ref_no: Sequelize.STRING(250),
    invoice_number: Sequelize.STRING,
    item_count: Sequelize.INTEGER,
    name_of_business: Sequelize.STRING(250),
    address_of_property: Sequelize.STRING(250),
    type_of_property: Sequelize.STRING(250),
    annaul_value: Sequelize.DECIMAL(50),
    rate_payable: Sequelize.DECIMAL(50),
    arrears: Sequelize.DECIMAL(50),
    grand_total: Sequelize.DECIMAL(50),
    remark: Sequelize.STRING(250),
    service_id: Sequelize.STRING(250) ,
    rate_year: Sequelize.STRING(100),
    rate_district: Sequelize.STRING(255),
    previous_balance: Sequelize.DECIMAL(50),
    penalty: Sequelize.STRING(100),
    goodwill: Sequelize.DECIMAL(50),
    payment_status: Sequelize.TINYINT(1),
    date_uploaded: Sequelize.DATE,
    phone_number: Sequelize.STRING(20),
    invoice_status: Sequelize.TINYINT,
    ass_status: Sequelize.TINYINT,
    state_tin: Sequelize.STRING,
    invoice: Sequelize.STRING,
    generated_phone: Sequelize.STRING,
    premises_inspection: Sequelize.DECIMAL,
    shop_rate: Sequelize.DECIMAL,
    sign_post: Sequelize.DECIMAL,
    category: Sequelize.STRING(100),
    tax_office_id: Sequelize.STRING,
    amount_paid: Sequelize.DECIMAL(50),
    payment_date: Sequelize.DATE,
    street:Sequelize.STRING,
    batch:Sequelize.STRING,
    market:Sequelize.STRING,
    cda:Sequelize.STRING,
    street_naming:Sequelize.STRING,
    updated_on: Sequelize.DATE,
    updated_by: Sequelize.STRING,
    image_url: Sequelize.STRING,
    email: Sequelize.STRING,
    rrr: Sequelize.STRING,
    item_count: Sequelize.INTEGER,
    arrear_relief_amount: Sequelize.DECIMAL(50)
},{
    timestamps : false,
    freezeTableName: true,
});

module.exports = Revenue_upload